title: Ananya Raghupathy # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
  Data Scientist with 3+ years of experience in Machine learning and Model lifecycle management. Holds a Master's in Data Analytics and Business Intelligence from Carnegie Mellon University. 
  <br><br>
  Currently building model monitoring solutions at <a href="https://agentblog.nationwide.com/agency-management/technology/predictive-analytics-in-insurance-5-uses-and-benefits/">Nationwide Insurance</a>. Previously at <a href="https://www.jifflenow.com/">Jifflenow</a>, <a href="https://www.us-ignite.org/program/smart-bases-and-installations/fort-carson/">US Ignite</a>, and <a href="https://www.drdo.gov.in/drdo/labs-and-establishments/centre-air-borne-system-cabs">Defence R&D Organization</a>
  <br><br>
  <a href="https://www.linkedin.com/in/ananyakr99/">View my LinkedIn Profile</a> 
  <a href="https://news.nationwide.com/image/94afdc36-9433-4f1c-a7cd-7a6b2a83709b/history-of-ai-at-nationwide2.jpg" target="_new"><img src="https://news.nationwide.com/image/94afdc36-9433-4f1c-a7cd-7a6b2a83709b/800/history-of-ai-at-nationwide2.jpg?10000" alt="infographic" border="0" /></a>
theme: jekyll-theme-minimal
google_analytics: G-XRB4G3V8LB # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
