title: Ananya Kalavala Raghupathy # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
  Data Scientist with 2+ years of commercial experience in Analytics, Machine Learning and Model Lifecycle Management and a Master's degree in Information Systems with a specialization in Data Analytics from Carnegie Mellon University. Currently building model monitoring solutions at Nationwide Insurance. Previously at Jifflenow, US Ignite and Defence R&D Organization.
  <br><br>
  <a href="https://www.linkedin.com/in/ananyakr99/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-XRB4G3V8LB # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
